apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  restartPolicy: Always
  containers:
  - name: default
    image: pod-image:latest
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 64Mi
