on:
  workflow_dispatch:
    inputs:
      image:
        description: image name we're updating
        required: true
      tag:
        description: new image tag
        required: true

jobs:
  update-kustomization:
    runs-on: ubuntu-latest
    steps:
    - name: event-information
      run: |
        echo "Event Information"
        echo "  name : ${{ github.event.inputs.name }}"
        echo "  image: ${{ github.event.inputs.image }}"

    - uses: imranismail/setup-kustomize@v1
    - uses: actions/checkout@v2

    - name: update-image
      working-directory: ./workflow-trigger
      run: |
        kustomize edit set image ${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}

    - name: commit-update
      run: |
        git config --local user.name "actions-user"
        git config --local user.email "actions-user@github.com"
        git add workflow-trigger
        git commit -m 'update image ${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}'

    - name: push-update
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    - name: print-kustomization
      working-directory: ./workflow-trigger
      run: |
        kustomize build .
